name: Update readme.md
on:
  schedule:
    - cron: '0 */20 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install dependencies
        run: yarn

      - name: Set env
        run: echo "workspace=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(env) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Git reset
        run: git reset --hard origin/master

      - name: Run script to update the content
        run: yarn build && yarn start
        env:
          ENVIRONMENT: production
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY  }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          WORKSPACE_PATH: ${{ env.workspace }}

      - name: Commit files
        run: git commit -am "[GITHUB-ACTIONS] Automatic readme update."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
